### ISSUE TITLE
"Voila" (Swap success page) should show details

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-frontend#106]
### You sent `X` `coin_a` and received `Y` `coin_b`.
You paid `Y` `coin_b` in fees ( `Z` %) for this.

That would be great I think.

**Comment by ImmanuelSegol** [comment]
@armurbalda Thanks for the feedback!
I think this is a necessary feature.
 @michael1011 @peartobear  Any opinions?

**Comment by peartobear** [comment]
@peartobear Yes you can go ahead with it, if you don't have any other critical tech debt on your plate.
