### ISSUE TITLE
Click on block explorer link brings up warning

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-frontend#109]
First click on it worked, second time:

![image](https://user-images.githubusercontent.com/16877539/53231227-b6182a80-3688-11e9-9114-c99d72e1564a.png)

EDIT:
Oh, actually it's a backend/middleware issue I believe since my swap didn't get an ID assigned, and the link in "click here" was just https://testnet.boltz.exchange/ which I guess it just defaulted to.

**Comment by michael1011** [comment]
This is related to the `createreverseswap` API endpoint not returning any data and stalling.
