### ISSUE TITLE
Reverse Swap Failure page - Retry link doesn't work

### ISSUE THREAD

**Issue by armurbalda** [BoltzExchange/boltz-frontend#110]
![image](https://user-images.githubusercontent.com/16877539/53231673-c977c580-3689-11e9-93e7-742c8d541f7e.png)

**Comment by michael1011** [comment]
Maybe the same bug as #109

**Comment by ImmanuelSegol** [comment]
@michael1011 @peartobear This issue has been resolved as far as I can see by backend and middleware fixes, correct? 
If so we should close this issue.
