### ISSUE TITLE
Show "Lost connection" message in a more beautiful way

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-frontend#123]
Related to the changes of #119 

Right now there is a simple `window.alert` message that tells the user that the connection got interrupted. That message should be replaced with a more beautiful one. I am thinking of something like this: https://teodosii.github.io/react-notifications-component/

A component like the one mentioned is more suitable because it can stay visible to the user until the connection is established again and also have a "reconnect" button.

**Comment by ImmanuelSegol** [comment]
@michael1011 @peartobear Where should we locate the indicator?

**Comment by michael1011** [comment]
@ImmanuelSegol I would go for the bottom left hand corner
