### ISSUE TITLE
"Swap Again" button not clickable

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-frontend#143]
When the swap is done, this canvas (see attached pic) is above all the other elements and it is blocking the input. 

![IMG_769735DE0691-1](https://user-images.githubusercontent.com/44926540/55469367-f8456c00-5637-11e9-9cb2-d5920c6abb79.jpeg)

**Comment by michael1011** [comment]
This does not happen locally for some reason. I will have another look at this issues once we deployed the latest master of the frontend to the instances

**Comment by ImmanuelSegol** [comment]
@michael1011 @peartobear I built the project and served it locally and this bug does not occur, **does this only happen in the VM?**

**Comment by michael1011** [comment]
This was fixed by @ImmanuelSegol!
