### ISSUE TITLE
Notify if Webln not detected

### ISSUE THREAD

**Issue by MikeD123** [BoltzExchange/boltz-frontend#150]
**Apologies if this is a duplicate issue**
Visiting the site without webln allows me to play with the numbers.

After trying something that exceeded the amount of liquidity, it said invalid amount.

Refreshing the page then leaves the exchange window un-clickable in the UI.

//

It would be great if the webln detect was done upfront, if not detected then grey out the module with a "Install Joule" button over the top.

Awesome work regardless, start of something rad, and ping me if I can ever be helpful or contribute in any way!

Get #reckless

**Comment by MikeD123** [comment]
Browser: Version 73.0.3683.86
MacOS.

Webln not installed.
Tried both incognito browser and standard.

**Comment by armurbalda** [comment]
I'd break that down in

One feature request:
"Install Joule" button if no WebLN detected

One bug report:
Open boltz.exchange with valid values, change these to sth invalid, refresh page - un-clickable UI. No WebLN.

I couldn't reproduce the bug so far with Chrome 73.0.3683.86 on Ubuntu 18.04 and latest Win 10. Can somebody with MacOS give it a shot? @peartobear Can you reliably reproduce this? If so: with Joule active it doesn't occur? @MikeD123

**Comment by peartobear** [comment]
I wasn't able to reproduce this in MacOS Sierra with Chrome 73.0.3683.86. I'll look more into it,
