### ISSUE TITLE
Make the blue button clickable only once

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-frontend#179]
Boltz needs a few seconds to check for the available routes and if the end user clicks the blue button second time before that, it throws a `failed to execute swap: route undefined` error. Make the blue button click event only executed once, irrespective of the number of times user clicks/taps on it. 

Reproducible on any setup. 

Expected behavior: Make the blue button click event only executed once, irrespective of the number of times user clicks/taps on it.

**Comment by michael1011** [comment]
This issue is about the button that causes a normal swap to get created.
