### ISSUE TITLE
Indicate whether file was uploaded successfully

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-frontend#20]
The dropdown field on the first page of the refund flow should indicate when a file was uploaded successfully. This could be done by replacing the dropdown field with the information that was inside of the uploaded file. That would also give the user the chance to verify that the correct file was selected.

Any other opinions? @ImmanuelSegol @peartobear

**Comment by peartobear** [comment]
Agree. Also, Please make sure user cannot click on "Next" to go to "Step 2" of refund until any file is uploaded. Grey out the next button for first state. @ImmanuelSegol
