### ISSUE TITLE
Drag/Drop or Select file for refund doesn't work

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-frontend#22]
Drag and dropping the `refund.json` file or selecting it from the local machine shows inactivity when tested using Google Chrome

**Comment by ImmanuelSegol** [comment]
I cant reproduce this, I'm on chrome `Version 71.0.3578.98 (Official Build) (64-bit)`

**Comment by ImmanuelSegol** [comment]
Could you send me the file you are using @peartobear

**Comment by ImmanuelSegol** [comment]
@peartobear I'm unable to reproduce this.
The file is properly uploaded when I drop or select it.
@michael1011 Are you experiencing this?

**Comment by ImmanuelSegol** [comment]
@peartobear I haven't been able to reproduce this and I don't think @michael1011 was able to either, we also haven't gotten any feedback from users on this issue.

The code for drag/drop or select files is supported on all browsers as far as I have tested. 

We should close the issue.
