### ISSUE TITLE
LN URL for mobile PWA site 

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-frontend#232]
A Boltz mobile PWA could automatically open LNURL-supporting wallet instead of user needing to copy paste the invoice

**Comment by michael1011** [comment]
Also show LNURL QR code on desktop to make using invoices from a mobile wallet easier

**Comment by michael1011** [comment]
LNURL spec for reference: https://github.com/btcontract/lnurl-rfc
