### ISSUE TITLE
Unable to upload refund.png

### ISSUE THREAD

**Issue by kn0wmad** [BoltzExchange/boltz-frontend#234]
I'm sorry if this is not the correct place for this - I could not find any other support options

**Describe the bug**
It appears that I am unable to upload my refund.png file after an unsuccessful swap

**To Reproduce**
1. Go to 'Refund'
2. Click on (or drag to) select file
3. Enter tx hash
4. Nothing happens, and I cannot progress by clicking Upload refund file

**Expected behavior**
I expected some verification that file had been uploaded, and then to be able to proceed in the refund flow

**Desktop (please complete the following information):**
 - OS: Linux (I have tried on Ubuntu and Arch)
 - Browser: I have tried FF and Brave
 - Browser Version: FF 76 and Brave 1.9.76 (Chromium 81)

**Additional context**
Thank you very much for any help you can provide.  I was a bit #reckless with this particular tx so I would very much like to get the refund so I can try again.  Thanks for what you're building here!

**Comment by peartobear** [comment]
Hello @kn0wmad, We just tried the refund flow on FF running on Ubuntu and it seem to be working fine. Could you please send us the swapID so we can see what went down. You can also privately DM us on twitter.com/boltzhq so we can debug this issue together. No worries. The swaps on Boltz are trust minimized and you will be able to refund your coins as long as you have access to the refund png file.

**Comment by kn0wmad** [comment]
Good day, thank you for the quick response.

The swap id is IArUiL

I was concerned that it was a problem local to me, but other than turning off browser extensions, I was at a loss as to what else I could try.

**Comment by michael1011** [comment]
Yeah there are some coins stuck in the Swap `IArUiL` :thinking: 

@kn0wmad  could you try refunding in an incognito browser window with all extensions disabled? I'll try to reproduce this issue bu have never had problems with refund files in Firefox myself...

**Comment by kn0wmad** [comment]
Just tried icognito without extensions, no dice.  This is a fairly recent (clean) install of Ubuntu 20.04, so I'm kind of at a loss at this point as I've tried on multiple PCs and browsers.  I'm fairly sure it's on my end, as I often get the strangest of the software gremlins.  

Not sure if this is helpful - I opened the console while uploading the file and after opening the file it throws:
Error: decode failed                                      qrcode-parser.cjs.js:94:15

**Comment by michael1011** [comment]
> Is it supposed to contain a qr code?

Yes, it should contain a QR code. That QR code encodes a private key and other required data for refunding. The file being blank explains why he refund didn't work.

Could you DM us on [Twitter](https://twitter.com/boltzhq) or join our [Discord](https://discord.gg/CMYKUCB) so that we can find a way to get these coins back?

**Comment by peartobear** [comment]
Discussion moved to other channels.
