### ISSUE TITLE
tried to parse address with `\n` in it

### ISSUE THREAD

**Issue by antonilol** [BoltzExchange/boltz-frontend#236]
**Describe the bug**

a swap is 'waiting for transaction' but the transaction is already there

i opened `F12` tab and saw this

```js
Uncaught (in promise) Error: tb1qea2kzlul85r94snmxr9ln7ktgesas3qyf0pg0j
 has no matching Script
    at Object.t.toOutputScript (address.js:89:9)
    at C (reverseDuck.js:150:15)
    at reverseDuck.js:212:30
    at u (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97:21)
    at n (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
```

in the `localStorage` i found `address: 'tb1qea2kzlul85r94snmxr9ln7ktgesas3qyf0pg0j\n'` (note the `\n`), apparently i added a return in the input box
in js this is easy to fix with `String.trim()`

**To Reproduce**
(i think but am not sure)
do a reverse submarine swap and enter your address with a return (`\n`) after it 

**Expected behavior**

normal flow of a swap

**Desktop (please complete the following information):**
 - OS: linux
 - Browser chromium
 - Browser Version [e.g. 22]

**Additional context**

**Comment by armurbalda** [comment]
Thanks for the report! Did you see this on https://boltz.exchange ?

**Comment by antonilol** [comment]
Sort of yes, it was testnet.boltz.exchange
