### ISSUE TITLE
testnet exchange doesn't work, Failed to fetch pairs

### ISSUE THREAD

**Issue by antonilol** [BoltzExchange/boltz-frontend#237]
**Describe the bug**

![image](https://user-images.githubusercontent.com/49868160/164291013-16bdd7be-a7cb-4e36-9688-8661f39a1125.png)

**To Reproduce**
1. Go to https://testnet.boltz.exchange/
2. See error

**Expected behavior**

the button becomes blue and you can click it

**Desktop (please complete the following information):**
 - OS: linux
 - Browser chromium
 - Browser Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser Version [e.g. 22]

**Additional context**

**Comment by michael1011** [comment]
Back online :v:

**Comment by antonilol** [comment]
i get this error on the mainnet site now, testnet works fine

**Comment by antonilol** [comment]
nvm it works again
