### ISSUE TITLE
Make button grey when next step is not available

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-frontend#27]
Regarding the waiting for events I introduced in #21

**Comment by ImmanuelSegol** [comment]
@michael1011 Shouldn't we just display the loading icon as we do with the `swap flow` and `refund flow`?

**Comment by michael1011** [comment]
It should be clear to the user that the button is not clickable. Do you guys think a loading icon is sufficient? @ImmanuelSegol @peartobear

**Comment by ImmanuelSegol** [comment]
@michael1011 I think it is because it indicated that we are still fetching the rates. 
Later on, we should add a loading page, or use #32  a modal to indicate that the app is still fetching data.

**Comment by michael1011** [comment]
I think I forgot to add a loading icon in #21. When you open the page it gets the rates from the middleware and just shows nothing (no rates or currencies) until it gets a response.

Could you also take care of that in this issue @ImmanuelSegol?

I am fine with a loading icon. @peartobear any objections?

**Comment by ImmanuelSegol** [comment]
@peartobear What should the loading icons look like for the rates and currencies just text saying loading or some animation?

**Comment by peartobear** [comment]
I think you should grey out the button and replace it with "Loading (32%.. )" and once it gets to 100%, reactivate the icon.

**Comment by michael1011** [comment]
It doesn't make a lot of sense to show percents when all you do is download a little JSON and iterate over it a twice.

I would just go for `Loading`. What about greying out the button if it can't be clicked? It is not completely necessary but a visual contrast would be nice to have.

**Comment by peartobear** [comment]
Lets go for `Loading` and greying out the button for now in this case.

**Comment by michael1011** [comment]
Then the button should be greyed out every time something is loading in the background? What if the user didn't provide required values or entered invalid ones? Should the button be greyed out too?

**Comment by peartobear** [comment]
IMO it should stay greyed out, We can show the error by what @ImmanuelSegol proposed here https://github.com/BoltzExchange/boltz-frontend/issues/32 or a bootstrap-esque red/pink horizentle banner on the top.

**Comment by ImmanuelSegol** [comment]
@michael1011 @peartobear Yeah I think we should take care of this as follows:

- `Start Swap` should be grey as long as the user didn't provide the required values.
- Any error with fetching rates or anything else for that matter should be dealt with by #32.

Another proposal would be to add a loading screen where we could load all the required assets and resources. And #32 will deal with any fetch errors occurring when executing swaps or refunds.
Opinions?

**Comment by michael1011** [comment]
I think a loading screen is overkill. I would go for the first proposal.

> If so this issue would only deal with greying out Start swap if the user didn't enter valid data.

I agree on this one. This way the user is aware that he can't go to the next step.
