### ISSUE TITLE
Swap flow refactoring

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-frontend#28]
A flow like:

1. amounts
2. invoice
3. refund file
4. address and QR code with button that waits for events

would make more sense because:

- the user gets the refund file before he sends any funds
- the screen on which the user sends onchain funds is also the one on which he waits for the transaction to confirm

Any opinions on that one? @ImmanuelSegol @peartobear

**Comment by peartobear** [comment]
Wait for me to refactor this UI mockup. @ImmanuelSegol
