### ISSUE TITLE
Show swap id to the user

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-frontend#29]
The response of the API call `createSwap` contains an `id`. That `id` should be shown to the user all time to make sure that we can identify the swap and what went wrong in case the swap doesn't work.

Edit: we should have a final decision on https://github.com/BoltzExchange/boltz-middleware/issues/18 before implementing this

**Comment by ImmanuelSegol** [comment]
@peartobear @michael1011 Where should we display the ID on the UI?

**Comment by peartobear** [comment]
Wait for #28

**Comment by michael1011** [comment]
Closed by https://github.com/BoltzExchange/boltz-frontend/pull/66
