### ISSUE TITLE
Banner component

### ISSUE THREAD

**Issue by ImmanuelSegol** [BoltzExchange/boltz-frontend#32]
@michael1011 @peartobear 
Implement a boostrap-esuqe banner, this banner should be used for:

- Provide feedback on failed swap/refund attempts.
- Provide feedback on recent events that are of import to the user.

**Comment by peartobear** [comment]
Do you mean boostrap-esuqe red banner or an entirely new box? @ImmanuelSegol

**Comment by ImmanuelSegol** [comment]
@peartobear I was thinking of an entirely new box but a banner would be better didn't think of that.

**Comment by peartobear** [comment]
We should check this out @michael1011 @ImmanuelSegol  https://getbootstrap.com/docs/4.0/components/alerts/

**Comment by ImmanuelSegol** [comment]
This issue is obsolete we have already found a solution to this problem
