### ISSUE TITLE
Brainstorm the best way to redirect user to block explorer and gauge its necessity

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-frontend#46]
Brainstorm the UX feasibility of putting a link to blockexplorer while in waiting state. 

Current mockup: 

![screen shot 2019-01-05 at 11 31 04 pm](https://user-images.githubusercontent.com/44926540/50726023-f86dc280-1141-11e9-8323-6d27ba169f0d.png)

**Comment by michael1011** [comment]
Possible solutions:
- make the text "Waiting for transaction to confirm" clickable and redirect to the block explorer
- replace the address and QR code with the transaction hash (and a link to a block explorer) once Boltz finds the transaction in the mempool
