### ISSUE TITLE
Automatically change the rate when switching assets

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-frontend#52]
Switching of assets doesn't trigger the default rate to change. As an expected behaviour,, the hardcoded rate should be recalculated and autofilled as soon as user switches any asset on home screen.

**Comment by michael1011** [comment]
Doesn't it already do that?

**Comment by peartobear** [comment]
I checked, it doesn't..

**Comment by michael1011** [comment]
Closed by https://github.com/BoltzExchange/boltz-frontend/pull/65
