### ISSUE TITLE
Hardcode the rate to 1:1 for same asset onchain and offchain

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-frontend#57]
Currently, while choosing BTC-lightning and BTC respectively in the both asset choose field, the edit of the text field gets disabled while the rates remained same (not 1:1) Change the rates of following asset combination to 1:1 

- LTC/LTC (lightjing or onchain)
- BTC/BTC (lightjing or onchain)

**Comment by michael1011** [comment]
Closed by https://github.com/BoltzExchange/boltz-middleware/pull/36
