### ISSUE TITLE
[Bug] Multiple clicks on blue/grey continue bar cause swap to fail 

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/boltz-frontend#69]
Clicking multiple times on the blue or grey button while in waiting state causes the app to crash and "swap fail" message to appear. Reproduce and investigate this issue. I guess, disabling any onClick() event to be sent while the button is already clicked once might fix this issue

**Comment by michael1011** [comment]
Related to: https://github.com/BoltzExchange/boltz-backend/issues/33
