### ISSUE TITLE
Remember pending swaps

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-frontend#75]

**Comment by ImmanuelSegol** [comment]
@michael1011 @peartobear 
We could cache the pending swaps on the client side and have an event that alerts when a swap is no longer pending.

If the user shuts down the browser then opens it agine and the cache has pending swaps we can make a call to the API that will update the current status of the cache.

I think this would be a good starting point for now, what are your opinions?

**Comment by michael1011** [comment]
I think we should focus on the [mainnet milestone](https://github.com/BoltzExchange/boltz-frontend/milestone/1) first. This is just a rough idea.

Also we would have to define *what* a pending swap is. After the user clicked start? Or is it just pending if the user has to wait for a transaction to confirm?
